config/routes.rb
Rails.application.routes.draw do
  resources :order_items
  resources :orders
  root 'orders#index'
  resources :pizza_types
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
	has_many :order_items
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :pizza_type
  belongs_to :order
end

app/models/pizza_type.rb
class PizzaType < ApplicationRecord
	validates :name, presence: true
	validates :price, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  before_action :set_order_item, only: [:show, :edit, :update, :destroy]

  # GET /order_items
  # GET /order_items.json
  def index
    @order_items = OrderItem.all
  end

  # GET /order_items/1
  # GET /order_items/1.json
  def show
  end

  # GET /order_items/new
  def new
    @order_item = OrderItem.new
  end

  # GET /order_items/1/edit
  def edit
  end

  # POST /order_items
  # POST /order_items.json
  def create
    @order_item = OrderItem.new(order_item_params)

    respond_to do |format|
      if @order_item.save
        format.html { redirect_to @order_item, notice: 'Order item was successfully created.' }
        format.json { render :show, status: :created, location: @order_item }
      else
        format.html { render :new }
        format.json { render json: @order_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /order_items/1
  # PATCH/PUT /order_items/1.json
  def update
    respond_to do |format|
      if @order_item.update(order_item_params)
        format.html { redirect_to @order_item, notice: 'Order item was successfully updated.' }
        format.json { render :show, status: :ok, location: @order_item }
      else
        format.html { render :edit }
        format.json { render json: @order_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /order_items/1
  # DELETE /order_items/1.json
  def destroy
    @order_item.destroy
    respond_to do |format|
      format.html { redirect_to order_items_url, notice: 'Order item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order_item
      @order_item = OrderItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_item_params
      params.require(:order_item).permit(:pizza_type_id, :quantity, :order_id)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
    @pizza_types = PizzaType.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.fetch(:order, {})
    end
end

app/controllers/pizza_types_controller.rb
class PizzaTypesController < ApplicationController
  before_action :set_pizza_type, only: [:show, :edit, :update, :destroy]

  # GET /pizza_types
  # GET /pizza_types.json
  def index
    @pizza_types = PizzaType.all
  end

  # GET /pizza_types/1
  # GET /pizza_types/1.json
  def show
  end

  # GET /pizza_types/new
  def new
    @pizza_type = PizzaType.new
  end

  # GET /pizza_types/1/edit
  def edit
  end

  # POST /pizza_types
  # POST /pizza_types.json
  def create
    @pizza_type = PizzaType.new(pizza_type_params)

    respond_to do |format|
      if @pizza_type.save
        format.html { redirect_to @pizza_type, notice: 'Pizza type was successfully created.' }
        format.json { render :show, status: :created, location: @pizza_type }
      else
        format.html { render :new }
        format.json { render json: @pizza_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pizza_types/1
  # PATCH/PUT /pizza_types/1.json
  def update
    respond_to do |format|
      if @pizza_type.update(pizza_type_params)
        format.html { redirect_to @pizza_type, notice: 'Pizza type was successfully updated.' }
        format.json { render :show, status: :ok, location: @pizza_type }
      else
        format.html { render :edit }
        format.json { render json: @pizza_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pizza_types/1
  # DELETE /pizza_types/1.json
  def destroy
    @pizza_type.destroy
    respond_to do |format|
      format.html { redirect_to pizza_types_url, notice: 'Pizza type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pizza_type
      @pizza_type = PizzaType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pizza_type_params
      params.require(:pizza_type).permit(:name, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pizza_types_helper.rb
module PizzaTypesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pizza</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/order_items/_form.html.erb
<%= form_with(model: order_item, local: true) do |form| %>
  <% if order_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order_item.errors.count, "error") %> prohibited this order_item from being saved:</h2>

      <ul>
      <% order_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :pizza_type_id %>
    <%= form.text_field :pizza_type_id %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity %>
  </div>

  <div class="field">
    <%= form.label :order_id %>
    <%= form.text_field :order_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/order_items/edit.html.erb
<h1>Editing Order Item</h1>

<%= render 'form', order_item: @order_item %>

<%= link_to 'Show', @order_item %> |
<%= link_to 'Back', order_items_path %>

app/views/order_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Order Items</h1>

<table>
  <thead>
    <tr>
      <th>Pizza type</th>
      <th>Quantity</th>
      <th>Order</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @order_items.each do |order_item| %>
      <tr>
        <td><%= order_item.pizza_type %></td>
        <td><%= order_item.quantity %></td>
        <td><%= order_item.order %></td>
        <td><%= link_to 'Show', order_item %></td>
        <td><%= link_to 'Edit', edit_order_item_path(order_item) %></td>
        <td><%= link_to 'Destroy', order_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order Item', new_order_item_path %>

app/views/order_items/new.html.erb
<h1>New Order Item</h1>

<%= render 'form', order_item: @order_item %>

<%= link_to 'Back', order_items_path %>

app/views/order_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pizza type:</strong>
  <%= @order_item.pizza_type %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @order_item.quantity %>
</p>

<p>
  <strong>Order:</strong>
  <%= @order_item.order %>
</p>

<%= link_to 'Edit', edit_order_item_path(@order_item) %> |
<%= link_to 'Back', order_items_path %>

app/views/orders/_form.html.erb
<%= form_with(model: order, local: true) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pizza Types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
    </tr>
  </thead>

  <tbody>
    <% @pizza_types.each do |pizza_type| %>
      <tr>
        <td><%= pizza_type.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

app/views/pizza_types/_form.html.erb
<%= form_with(model: pizza_type, local: true) do |form| %>
  <% if pizza_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pizza_type.errors.count, "error") %> prohibited this pizza_type from being saved:</h2>

      <ul>
      <% pizza_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pizza_types/edit.html.erb
<h1>Editing Pizza Type</h1>

<%= render 'form', pizza_type: @pizza_type %>

<%= link_to 'Show', @pizza_type %> |
<%= link_to 'Back', pizza_types_path %>

app/views/pizza_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pizza Types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pizza_types.each do |pizza_type| %>
      <tr>
        <td><%= pizza_type.name %></td>
        <td><%= pizza_type.price %></td>
        <td><%= link_to 'Show', pizza_type %></td>
        <td><%= link_to 'Edit', edit_pizza_type_path(pizza_type) %></td>
        <td><%= link_to 'Destroy', pizza_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pizza Type', new_pizza_type_path %>

app/views/pizza_types/new.html.erb
<h1>New Pizza Type</h1>

<%= render 'form', pizza_type: @pizza_type %>

<%= link_to 'Back', pizza_types_path %>

app/views/pizza_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pizza_type.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @pizza_type.price %>
</p>

<%= link_to 'Edit', edit_pizza_type_path(@pizza_type) %> |
<%= link_to 'Back', pizza_types_path %>